#ifndef GENERALFUNCTIONS_GLOBAL_H
#define GENERALFUNCTIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef GENERALFUNCTIONS_LIB
# define GENERALFUNCTIONS_EXPORT Q_DECL_EXPORT
#else
# define GENERALFUNCTIONS_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERALFUNCTIONS_GLOBAL_H
