#ifndef HANDPOINTSPROVIDER_GLOBAL_H
#define HANDPOINTSPROVIDER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef HANDPOINTSPROVIDER_LIB
# define HANDPOINTSPROVIDER_EXPORT Q_DECL_EXPORT
#else
# define HANDPOINTSPROVIDER_EXPORT Q_DECL_IMPORT
#endif

#endif // HANDPOINTSPROVIDER_GLOBAL_H
